<template>
  <div class="admin-shell" v-if="assessment"><header class="admin-heading"><div><router-link to="/admin/content" class="text-sm font-bold text-gray-500">← Контент</router-link><h1 class="mt-3 text-3xl font-black">{{ assessment.title }}</h1><p class="mt-2 text-gray-500">Редактирование создаёт черновик. Ученики продолжат видеть последнюю опубликованную версию.</p></div><button class="btn-primary" :disabled="publishing" @click="publish">{{ publishing ? 'Публикую…' : 'Опубликовать версию' }}</button></header>
    <p v-if="message" class="mb-4 rounded-xl bg-green-50 p-3 text-sm text-green-700">{{ message }}</p>
    <div class="space-y-4"><article v-for="(question, index) in assessment.questions" :key="question.id" class="card"><div class="flex items-center justify-between"><p class="eyebrow text-primary-600">Вопрос {{ index + 1 }} · {{ question.type }}</p><span class="text-sm text-gray-500">{{ question.points }} баллов</span></div><label class="form-group mt-4"><span class="form-label">Текст вопроса</span><textarea v-model="question.prompt" class="form-textarea" rows="2"></textarea></label><div class="form-group"><span class="form-label">Иллюстрация (PNG/JPG/WebP до 5 МБ)</span><img v-if="question.prompt_media_url" :src="question.prompt_media_url" alt="Иллюстрация вопроса" class="mb-3 max-h-56 rounded-xl object-contain"><input type="file" accept="image/png,image/jpeg,image/webp" class="text-sm" @change="upload(question, $event)"></div><label class="form-group"><span class="form-label">Правильный ответ (JSON)</span><textarea v-model="configs[question.id]" class="form-textarea font-mono text-xs" rows="3"></textarea></label><label class="form-group"><span class="form-label">Объяснение</span><textarea v-model="question.explanation" class="form-textarea" rows="2"></textarea></label><button class="btn-secondary" @click="save(question)">Сохранить вопрос</button></article></div>
  </div><div v-else class="card text-center">Загружаю редактор…</div>
</template>
<script setup lang="ts">
import {onMounted, ref} from 'vue'; import {useRoute} from 'vue-router'; import {learningApi} from '@/api/learning'; import {useWorkspaceStore} from '@/stores/workspace'; import type {AssessmentSummary, LearningQuestion} from '@/types/learning'
const route = useRoute(); const workspace = useWorkspaceStore(); const assessment = ref<(AssessmentSummary & {questions: LearningQuestion[]}) | null>(null); const configs = ref<Record<string, string>>({}); const message = ref(''); const publishing = ref(false)
onMounted(async () => { const current = await workspace.load(); if (!current) return; assessment.value = (await learningApi.editor(current.id, String(route.params.assessmentId))).assessment; for (const q of assessment.value.questions) configs.value[q.id] = JSON.stringify(q.answer_config, null, 2) })
async function save(question: LearningQuestion) { if (!workspace.current || !assessment.value) return; await learningApi.updateQuestion(workspace.current.id, assessment.value.id, question.id, {prompt: question.prompt, explanation: question.explanation, answer_config: JSON.parse(configs.value[question.id])}); message.value = 'Вопрос сохранён в черновик.' }
async function upload(question: LearningQuestion, event: Event) { if (!workspace.current || !assessment.value) return; const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; const response = await learningApi.uploadMedia(workspace.current.id, file, `Иллюстрация к вопросу: ${question.prompt}`); question.prompt_media_id = response.asset.id; question.prompt_media_url = response.asset.url; await learningApi.updateQuestion(workspace.current.id, assessment.value.id, question.id, {prompt_media_id: response.asset.id}); message.value = 'Иллюстрация загружена в черновик.' }
async function publish() { if (!workspace.current || !assessment.value) return; publishing.value = true; const response = await learningApi.publish(workspace.current.id, assessment.value.id) as {version: number}; assessment.value.current_version = response.version; message.value = `Опубликована версия ${response.version}.`; publishing.value = false }
</script>
