<template>
  <div class="admin-shell"><header class="admin-heading"><div><router-link to="/admin" class="text-sm font-bold text-gray-500">← Админка</router-link><h1 class="mt-3 text-3xl font-black">Новое назначение</h1><p class="mt-2 text-gray-500">Выберите опубликованный тест, ученика и при необходимости срок.</p></div></header>
    <form class="card mx-auto max-w-2xl space-y-5" @submit.prevent="assign"><label class="block"><span class="form-label">Тест</span><select v-model="form.assessment_id" class="form-select" required><option value="" disabled>Выберите тест</option><option v-for="item in published" :key="item.id" :value="item.id">{{ item.title }} · {{ item.target_grade }} класс</option></select></label><label class="block"><span class="form-label">Ученик</span><select v-model="form.learner_user_id" class="form-select" required><option value="" disabled>Выберите ученика</option><option v-for="learner in learners" :key="learner.id" :value="learner.id">{{ learner.name }} · {{ learner.target_grade }} класс</option></select></label><label class="block"><span class="form-label">Выполнить до</span><input v-model="form.due_at" type="datetime-local" class="form-input"></label><p v-if="message" class="rounded-xl bg-green-50 p-3 text-green-700">{{ message }}</p><button class="btn-primary w-full py-3" :disabled="saving">{{ saving ? 'Назначаю…' : 'Назначить тест' }}</button></form>
  </div>
</template>
<script setup lang="ts">
import {computed, onMounted, reactive, ref} from 'vue'; import {learningApi, workspaceApi} from '@/api/learning'; import {useWorkspaceStore} from '@/stores/workspace'; import type {AssessmentSummary} from '@/types/learning'
const workspace = useWorkspaceStore(); const assessments = ref<AssessmentSummary[]>([]); const learners = ref<Array<{id: string; name: string; target_grade: number}>>([]); const form = reactive({assessment_id: '', learner_user_id: '', due_at: ''}); const saving = ref(false); const message = ref(''); const published = computed(() => assessments.value.filter(item => item.status === 'published'))
onMounted(async () => { const current = await workspace.load(); if (!current) return; [assessments.value, learners.value] = [(await learningApi.assessments(current.id)).assessments, (await workspaceApi.learners(current.id)).learners] })
async function assign() { if (!workspace.current) return; saving.value = true; await learningApi.assign(workspace.current.id, {...form, due_at: form.due_at ? new Date(form.due_at).toISOString() : undefined}); message.value = 'Тест назначен. Он появился в плане ученика.'; form.assessment_id = ''; form.learner_user_id = ''; form.due_at = ''; saving.value = false }
</script>
