<template>
  <div class="admin-shell"><header class="admin-heading"><div><router-link to="/admin" class="text-sm font-bold text-gray-500">← Админка</router-link><h1 class="mt-3 text-3xl font-black">Учебный контент</h1><p class="mt-2 text-gray-500">Версионированные тесты из собственного или лицензированного материала.</p></div><button class="btn-primary" @click="showImport = !showImport">Импорт JSON</button></header>
    <section class="mb-6"><p class="eyebrow text-primary-600">Стартовая библиотека</p><div class="mt-3 grid gap-3 md:grid-cols-2"><article v-for="pack in libraryPacks" :key="pack.id" class="card flex items-start justify-between gap-4"><div><h2 class="font-black">{{ pack.title }}</h2><p class="mt-1 text-sm text-gray-500">{{ pack.description }} · целевой {{ pack.target_grade }} класс</p></div><button class="btn-primary shrink-0" :disabled="busy || installed(pack)" @click="installStarter(pack)">{{ installed(pack) ? 'Установлен' : 'Установить' }}</button></article></div></section>
    <section v-if="showImport" class="card mb-6"><h2 class="text-xl font-black">Learning Pack v1</h2><p class="mt-1 text-sm text-gray-500">Сначала проверим структуру и источник, затем создадим опубликованную версию.</p><textarea v-model="source" rows="12" class="form-textarea mt-4 font-mono text-xs" placeholder="Вставьте JSON-пакет"></textarea><p v-if="message" class="mt-3 text-sm" :class="message.startsWith('Ошибка') ? 'text-red-600' : 'text-green-600'">{{ message }}</p><div class="mt-4 flex gap-3"><button class="btn-secondary" :disabled="busy" @click="preview">Проверить</button><button class="btn-primary" :disabled="busy || !validated" @click="importPack">Импортировать</button></div></section>
    <div v-if="!assessments.length" class="empty-learning"><div class="text-5xl">📚</div><h2 class="mt-3 text-xl font-black">Каталог пока пуст</h2><p class="mt-1 text-gray-500">Импортируйте первый оригинальный пакет вопросов.</p></div>
    <div v-else class="grid gap-4 lg:grid-cols-2"><router-link v-for="item in assessments" :key="item.id" :to="`/admin/content/${item.id}`" class="task-card"><div class="subject-icon">{{ item.subject === 'math' ? '∑' : 'А' }}</div><div class="flex-1"><div class="flex gap-2"><span class="badge">{{ item.target_grade }} класс</span><span class="badge" :class="item.status === 'published' ? 'badge-success' : 'badge-warning'">{{ item.status }}</span></div><h2 class="mt-3 text-lg font-black">{{ item.title }}</h2><p class="mt-1 text-sm text-gray-500">Версия {{ item.current_version }} · программа {{ item.coverage_from_grade }}–{{ item.coverage_to_grade }} классов</p></div><span class="text-xl text-primary-500">→</span></router-link></div>
  </div>
</template>
<script setup lang="ts">
import {onMounted, ref} from 'vue'; import {learningApi} from '@/api/learning'; import {useWorkspaceStore} from '@/stores/workspace'; import type {AssessmentSummary} from '@/types/learning'
const workspace = useWorkspaceStore(); const assessments = ref<AssessmentSummary[]>([]); const showImport = ref(false); const source = ref(''); const message = ref(''); const busy = ref(false); const validated = ref(false)
type LibraryPack = {id: string; title: string; description: string; questions: number; target_grade: number}
const libraryPacks = ref<LibraryPack[]>([]); const installed = (pack: LibraryPack) => assessments.value.some(item => item.title === pack.title)
async function load() { const current = await workspace.load(); if (current) { assessments.value = (await learningApi.assessments(current.id)).assessments; libraryPacks.value = (await learningApi.library(current.id)).packs } }
function payload() { return JSON.parse(source.value) as unknown }
async function preview() { if (!workspace.current) return; busy.value = true; try { const result = await learningApi.importPreview(workspace.current.id, payload()) as {summary?: {question_count?: number}}; validated.value = true; message.value = `Проверка пройдена. Вопросов: ${result.summary?.question_count ?? '—'}` } catch (caught) { validated.value = false; message.value = `Ошибка: ${(caught as Error).message}` } finally { busy.value = false } }
async function importPack() { if (!workspace.current) return; busy.value = true; try { await learningApi.importPack(workspace.current.id, payload()); message.value = 'Пакет импортирован и опубликован.'; source.value = ''; validated.value = false; await load() } catch (caught) { message.value = `Ошибка: ${(caught as Error).message}` } finally { busy.value = false } }
async function installStarter(pack: LibraryPack) { if (!workspace.current) return; busy.value = true; try { await learningApi.installPack(workspace.current.id, pack.id); message.value = 'Стартовый пакет установлен.'; await load() } finally { busy.value = false } }
onMounted(load)
</script>
