<template>
  <div class="admin-shell"><header class="admin-heading"><div><router-link to="/admin" class="text-sm font-bold text-gray-500">← Админка</router-link><h1 class="mt-3 text-3xl font-black">Участники семьи</h1><p class="mt-2 text-gray-500">Детскому профилю не нужна почта — достаточно логина и PIN.</p></div><div class="flex gap-2"><button class="btn-secondary" @click="showInvite = !showInvite">Пригласить взрослого</button><button class="btn-primary" @click="showForm = !showForm">{{ showForm ? 'Закрыть' : 'Добавить ученика' }}</button></div></header>
    <form v-if="showInvite" class="card mb-6 flex flex-col gap-4 sm:flex-row sm:items-end" @submit.prevent="invite"><label class="flex-1"><span class="form-label">Email родителя или преподавателя</span><input v-model="inviteForm.email" type="email" class="form-input" required></label><label><span class="form-label">Роль</span><select v-model="inviteForm.role" class="form-select"><option value="admin">Администратор</option><option value="member">Наблюдатель</option></select></label><button class="btn-primary">Создать приглашение</button><div v-if="inviteUrl" class="basis-full rounded-xl bg-primary-50 p-3 text-sm"><p class="font-bold">Ссылка действует 7 дней</p><input class="mt-2 w-full bg-transparent text-xs" readonly :value="inviteUrl" @focus="($event.target as HTMLInputElement).select()"></div></form>
    <form v-if="showForm" class="card mb-6 grid gap-4 md:grid-cols-2" @submit.prevent="create">
      <label class="form-group mb-0"><span class="form-label">Имя</span><input v-model="form.name" class="form-input" required></label>
      <label class="form-group mb-0"><span class="form-label">Логин</span><input v-model="form.login" class="form-input" pattern="[A-Za-z0-9._-]{3,32}" required></label>
      <label class="form-group mb-0"><span class="form-label">PIN (4–8 цифр)</span><input v-model="form.pin" class="form-input" inputmode="numeric" pattern="[0-9]{4,8}" required></label>
      <label class="form-group mb-0"><span class="form-label">Текущий класс</span><select v-model.number="form.target_grade" class="form-select"><option v-for="grade in 11" :key="grade" :value="grade">{{ grade }}</option></select></label>
      <p v-if="error" class="text-sm text-red-600 md:col-span-2">{{ error }}</p><button class="btn-primary md:col-span-2" :disabled="saving">{{ saving ? 'Создаю…' : 'Создать профиль' }}</button>
    </form>
    <div class="grid gap-4 md:grid-cols-2"><article v-for="learner in learners" :key="learner.id" class="card"><div class="flex items-center gap-4"><div class="avatar">{{ learner.name[0] }}</div><div class="flex-1"><h2 class="font-black">{{ learner.name }}</h2><p class="text-sm text-gray-500">@{{ learner.login }} · {{ learner.target_grade }} класс</p></div><button class="text-sm font-bold text-primary-600" @click="editSchedule(learner)">Напоминания</button></div></article></div>
    <form v-if="scheduleLearner" class="card mt-6" @submit.prevent="saveSchedule"><div class="flex items-center justify-between"><div><p class="eyebrow text-primary-600">Расписание</p><h2 class="text-xl font-black">{{ scheduleLearner.name }}</h2></div><button type="button" class="text-gray-500" @click="scheduleLearner = null">✕</button></div><div class="mt-5 grid gap-4 md:grid-cols-3"><label><span class="form-label">Время занятия</span><input v-model="schedule.daily_time" type="time" class="form-input" required></label><label><span class="form-label">Напомнить родителю через</span><select v-model.number="schedule.guardian_delay_minutes" class="form-select"><option :value="30">30 минут</option><option :value="60">1 час</option><option :value="120">2 часа</option></select></label><label class="flex items-end gap-2 pb-3"><input v-model="schedule.enabled" type="checkbox" class="h-5 w-5"><span>Напоминания включены</span></label></div><div class="mt-4"><span class="form-label">Дни недели</span><div class="flex flex-wrap gap-2"><label v-for="day in days" :key="day.value" class="cursor-pointer rounded-xl border px-3 py-2 text-sm" :class="schedule.weekdays.includes(day.value) ? 'border-primary-500 bg-primary-50 text-primary-700' : 'border-gray-200'"><input v-model="schedule.weekdays" class="sr-only" type="checkbox" :value="day.value">{{ day.label }}</label></div></div><button class="btn-primary mt-5" :disabled="scheduleSaving">Сохранить расписание</button></form>
  </div>
</template>
<script setup lang="ts">
import {onMounted, reactive, ref} from 'vue'; import {learningApi, workspaceApi} from '@/api/learning'; import {useWorkspaceStore} from '@/stores/workspace'
type Learner = {id: string; name: string; login: string; target_grade: number; timezone: string}
const workspace = useWorkspaceStore(); const learners = ref<Learner[]>([]); const showForm = ref(false); const showInvite = ref(false); const saving = ref(false); const error = ref(''); const form = reactive({name: '', login: '', pin: '', target_grade: 1}); const inviteForm = reactive<{email: string; role: 'admin' | 'member'}>({email: '', role: 'admin'}); const inviteUrl = ref('')
const scheduleLearner = ref<Learner | null>(null); const scheduleSaving = ref(false); const schedule = reactive({timezone: 'Europe/Moscow', daily_time: '18:30', weekdays: [1, 2, 3, 4, 5], guardian_delay_minutes: 60, enabled: true}); const days = [{value: 1, label: 'Пн'}, {value: 2, label: 'Вт'}, {value: 3, label: 'Ср'}, {value: 4, label: 'Чт'}, {value: 5, label: 'Пт'}, {value: 6, label: 'Сб'}, {value: 7, label: 'Вс'}]
async function load() { const current = await workspace.load(); if (current) learners.value = (await workspaceApi.learners(current.id)).learners }
async function create() { if (!workspace.current) return; saving.value = true; error.value = ''; try { await workspaceApi.createLearner(workspace.current.id, form); Object.assign(form, {name: '', login: '', pin: '', target_grade: 1}); showForm.value = false; await load() } catch (caught) { error.value = (caught as Error).message } finally { saving.value = false } }
async function invite() { if (!workspace.current) return; inviteUrl.value = (await workspaceApi.invite(workspace.current.id, inviteForm)).accept_url }
async function editSchedule(learner: Learner) { if (!workspace.current) return; scheduleLearner.value = learner; const response = await learningApi.schedule(workspace.current.id, learner.id); Object.assign(schedule, response.schedule || {timezone: learner.timezone || 'Europe/Moscow', daily_time: '18:30', weekdays: [1, 2, 3, 4, 5], guardian_delay_minutes: 60, enabled: true}) }
async function saveSchedule() { if (!workspace.current || !scheduleLearner.value) return; scheduleSaving.value = true; await learningApi.saveSchedule(workspace.current.id, scheduleLearner.value.id, schedule); scheduleSaving.value = false }
onMounted(load)
</script>
